from django import template

register = template.Library()

_TRANSLATIONS = {
    "ar": {
        "Admin Login": "تسجيل دخول الإدارة",
        "Sign in using an admin account to access the dashboard.": "سجّل الدخول بحساب إداري للوصول إلى لوحة التحكم.",
        "Invalid credentials or not an admin user.": "بيانات الدخول غير صحيحة أو المستخدم ليس إداريًا.",
        "Back": "رجوع",
        "Username": "اسم المستخدم",
        "Password": "كلمة المرور",
        "Language": "اللغة",
        "Menu": "القائمة",
        "Sign In": "دخول",
        "Logout": "تسجيل الخروج",
        "Admin Home": "الصفحة الرئيسية للإدارة",
        "Manage all registered models from one page.": "إدارة جميع النماذج المسجلة من صفحة واحدة.",
        "Dashboard": "لوحة الإحصائيات",
        "Reports": "التقارير",
        "Audit Logs": "سجلات التدقيق",
        "Open Django Admin": "فتح لوحة Django",
        "Privileges Matrix": "مصفوفة الصلاحيات",
        "Audit Insights": "تحليلات التدقيق",
        "Attendance Exceptions": "استثناءات الحضور",
        "Manage": "إدارة",
        "No admin models available for your permissions.": "لا توجد نماذج متاحة لصلاحياتك.",
        "Model is not available in Django admin URLs.": "هذا النموذج غير متاح ضمن روابط Django admin.",
        "Insert and edit records.": "إدراج وتعديل السجلات.",
        "Home": "الرئيسية",
        "Add New": "إضافة جديد",
        "Search Name": "بحث بالاسم",
        "Search ID": "بحث بالمعرف",
        "Filter Date": "تصفية بالتاريخ",
        "Search Civil ID": "بحث بالرقم المدني",
        "Search Employee Number": "بحث برقم الموظف",
        "Search Employee": "بحث بالموظف",
        "Search Location": "بحث بالموقع",
        "Search User": "بحث بالمستخدم",
        "Search Description": "بحث في الوصف",
        "Actions": "الإجراءات",
        "Edit": "تعديل",
        "No records yet.": "لا توجد سجلات بعد.",
        "First": "الأول",
        "Previous": "السابق",
        "Next": "التالي",
        "Last": "الأخير",
        "List Page": "صفحة القائمة",
        "Cancel": "إلغاء",
        "Search options...": "ابحث في الخيارات...",
        "Select User": "اختر المستخدم",
        "Apply": "تطبيق",
        "Model": "النموذج",
        "Access Level": "مستوى الصلاحية",
        "Enabled": "مفعل",
        "Save Matrix": "حفظ المصفوفة",
        "No Access": "بدون صلاحية",
        "NO_ACCESS": "بدون صلاحية",
        "ALL_MODELS": "كل النماذج",
        "Read Only": "قراءة فقط",
        "READ_ONLY": "قراءة فقط",
        "Add Only": "إضافة فقط",
        "ADD_ONLY": "إضافة فقط",
        "Edit Only": "تعديل فقط",
        "EDIT_ONLY": "تعديل فقط",
        "All": "الكل",
        "ALL": "الكل",
        "Full Admin": "مدير كامل",
        "FULL_ADMIN": "مدير كامل",
        "Manage user privileges in one matrix by model.": "إدارة صلاحيات المستخدمين في مصفوفة واحدة حسب النموذج.",
        "Select a user to view and edit privileges.": "اختر مستخدمًا لعرض الصلاحيات وتعديلها.",
        "Read only access. Only FULL_ADMIN can update privileges.": "وصول للقراءة فقط. يمكن لـ FULL_ADMIN فقط تحديث الصلاحيات.",
        "Reports": "التقارير",
        "Generate PDF reports for your entity data.": "إنشاء تقارير PDF لبيانات جهتك.",
        "Employee Location Assignments": "تعيينات الموظفين على المواقع",
        "Includes assignment status, sign permissions, and start/end dates.": "يشمل حالة التعيين وصلاحيات التسجيل وتواريخ البداية/النهاية.",
        "Employee": "الموظف",
        "All Employees": "كل الموظفين",
        "Location": "الموقع",
        "All Locations": "كل المواقع",
        "Active": "نشط",
        "All": "الكل",
        "Yes": "نعم",
        "No": "لا",
        "Preview": "معاينة",
        "Download PDF": "تنزيل PDF",
        "Locations": "المواقع",
        "Includes location activity, GPS/beacon mode, coordinates, and radius.": "يشمل حالة الموقع ووضع GPS/Beacon والإحداثيات ونطاق GPS.",
        "Includes location activity, GPS/beacon mode, and coordinates.": "يشمل حالة الموقع ووضع GPS/Beacon والإحداثيات.",
        "Name Contains": "الاسم يحتوي",
        "GPS Based": "يعتمد على GPS",
        "Beacon Based": "يعتمد على Beacon",
        "Report": "تقرير",
        "No filters applied.": "لا توجد فلاتر مطبقة.",
        "No records found for current filters.": "لا توجد سجلات للفلاتر الحالية.",
        "Apply Filter": "تطبيق الفلتر",
        "Clear": "مسح",
        "From Date": "من تاريخ",
        "To Date": "إلى تاريخ",
        "Total Transactions": "إجمالي العمليات",
        "Today Transactions": "عمليات اليوم",
        "Total Failures": "إجمالي الإخفاقات",
        "Biometric Verification Failures": "إخفاقات التحقق الحيوي",
        "Total Locations": "إجمالي المواقع",
        "Sign Actions": "إجراءات التسجيل",
        "Failed Verifications": "عمليات تحقق فاشلة",
        "Failed Biometric Verifications": "عمليات تحقق حيوي فاشلة",
        "Note: failures here mean biometric verification failed, but attendance transaction was still inserted.": "ملاحظة: الإخفاقات هنا تعني فشل التحقق الحيوي، لكن تم إدراج عملية الحضور بنجاح.",
        "SIGN_IN Failed": "فشل SIGN_IN",
        "SIGN_CONFIRM Failed": "فشل SIGN_CONFIRM",
        "SIGN_OUT Failed": "فشل SIGN_OUT",
        "Top 50 Employees With Failed Biometric Verification": "أعلى 50 موظفًا في فشل التحقق الحيوي",
        "Employee ID": "معرف الموظف",
        "Employee Name": "اسم الموظف",
        "Employee No": "رقم الموظف",
        "Civil ID": "الرقم المدني",
        "Failed Count": "عدد الإخفاقات",
        "Last Failed At": "آخر وقت فشل",
        "No failed biometric records found.": "لا توجد سجلات فشل تحقق حيوي.",
        "Charts": "الرسوم البيانية",
        "Sign Actions": "إجراءات التسجيل",
        "Top Locations by Transactions": "أعلى المواقع حسب عدد العمليات",
        "Failed Transactions": "عمليات فاشلة",
        "Inactive": "غير نشط",
        "Entity Logo": "شعار الجهة",
        "Powered by AWS": "مدعوم بواسطة AWS",
        "Owned by SWAP KUWAIT": "مملوك لـ SWAP KUWAIT",
        "Quick Search": "بحث سريع",
        "Entity": "الجهة",
        "User": "المستخدم",
        "Page": "صفحة",
        "Action": "الإجراء",
        "of": "من",
        "Total Audit Logs": "إجمالي سجلات التدقيق",
        "Unique Users": "عدد المستخدمين المميزين",
        "Permission Denied Events": "أحداث رفض الصلاحيات",
        "Action Contains": "الإجراء يحتوي",
        "Model Contains": "النموذج يحتوي",
        "Description Contains": "الوصف يحتوي",
        "Export CSV": "تصدير CSV",
        "Export PDF": "تصدير PDF",
        "Top Actions": "أعلى الإجراءات",
        "Top Models": "أعلى النماذج",
        "Audit Log Details": "تفاصيل سجل التدقيق",
        "Created At": "تاريخ الإنشاء",
        "Object ID": "معرف السجل",
        "Description": "الوصف",
        "No audit logs found for current filters.": "لا توجد سجلات تدقيق للفلاتر الحالية.",
        "Review audit activity with filters, metrics, and exports.": "مراجعة نشاط التدقيق مع الفلاتر والمؤشرات والتصدير.",
        "Review attendance anomalies to follow up quickly.": "مراجعة شذوذات الحضور للمتابعة بسرعة.",
        "Failure Threshold": "حد الإخفاق",
        "Late After Hour": "متأخر بعد الساعة",
        "Late SIGN_IN Groups": "مجموعات SIGN_IN المتأخرة",
        "Missing SIGN_OUT By Day": "غياب SIGN_OUT حسب اليوم",
        "Outside Assigned Locations": "خارج المواقع المعينة",
        "Repeated Biometric Failures": "إخفاقات تحقق حيوي متكررة",
        "Date": "التاريخ",
        "SIGN_IN Count": "عدد SIGN_IN",
        "SIGN_OUT Count": "عدد SIGN_OUT",
        "Last SIGN_IN": "آخر SIGN_IN",
        "Transaction ID": "معرف العملية",
        "Occurred At": "وقت الحدوث",
        "No exception records found for current filters.": "لا توجد سجلات استثناء للفلاتر الحالية.",
        "Biometric Verification Failures": "إخفاقات التحقق الحيوي",
        "Failed Biometric Verifications": "عمليات تحقق حيوي فاشلة",
        "SIGN_IN Failed": "فشل SIGN_IN",
        "SIGN_CONFIRM Failed": "فشل SIGN_CONFIRM",
        "SIGN_OUT Failed": "فشل SIGN_OUT",
        "Employee ID": "معرف الموظف",
        "Employee Name": "اسم الموظف",
        "Employee No": "رقم الموظف",
        "Civil ID": "الرقم المدني",
        "Failed Count": "عدد الإخفاقات",
        "Last Failed At": "آخر وقت فشل",
        "No failed biometric records found.": "لا توجد سجلات فشل تحقق حيوي.",
        "Inactive": "غير نشط",
        "Entity Logo": "شعار الجهة",
        "Powered by AWS": "مدعوم بواسطة AWS",
        "Owned by SWAP KUWAIT": "مملوك لـ SWAP KUWAIT",
        "Note: failures here mean biometric verification failed, but attendance transaction was still inserted.": "ملاحظة: الإخفاقات هنا تعني فشل التحقق الحيوي، لكن تم إدراج عملية الحضور بنجاح.",
        "Save Filters": "حفظ الفلاتر",
        "Load Saved Filters": "تحميل الفلاتر المحفوظة",
        "Clear Saved Filters": "مسح الفلاتر المحفوظة",
        "Data Quality Checks": "فحوصات جودة البيانات",
        "Employees Missing Photo": "موظفون بدون صورة",
        "Duplicate Civil ID Groups": "مجموعات رقم مدني مكرر",
        "Duplicate Employee No Groups": "مجموعات رقم موظف مكرر",
        "GPS Locations Missing Coordinates": "مواقع GPS بدون إحداثيات",
        "Inactive Employees With Active Assignments": "موظفون غير نشطين بتعيينات نشطة",
        "Biometric API Health": "صحة واجهات التحقق الحيوي",
        "Health metrics are computed from attendance records that used FACE_COMPARE_API in the selected date range.": "مؤشرات الصحة محسوبة من سجلات الحضور التي استخدمت FACE_COMPARE_API ضمن نطاق التاريخ المحدد.",
        "Total API Checks": "إجمالي فحوصات الواجهة",
        "Passed Checks": "فحوصات ناجحة",
        "Failed Checks": "فحوصات فاشلة",
        "Liveness Failures": "إخفاقات الحيوية",
        "Liveness": "الحيوية",
        "Face Compare Failures": "إخفاقات مقارنة الوجه",
        "Last API Failure At": "آخر وقت فشل للواجهة",
        "Success Rate": "معدل النجاح",
        "Error Rate": "معدل الخطأ",
        "Change Summary": "ملخص التغييرات",
        "Field": "الحقل",
        "Old Value": "القيمة السابقة",
        "New Value": "القيمة الجديدة",
        "No field changes detected.": "لم يتم اكتشاف تغييرات في الحقول.",
        "Recommended: PNG/JPG, max 1 MB, square logo (e.g. 256x256).": "الموصى به: PNG/JPG بحجم أقصى 1 ميجابايت وشعار مربع (مثل 256x256).",
        "Approx size": "الحجم التقريبي",
        "Dimensions": "الأبعاد",
        "Warning: logo is larger than recommended 1 MB.": "تحذير: حجم الشعار أكبر من الحد الموصى به 1 ميجابايت.",
        "Deactivate": "إلغاء التفعيل",
        "Restore": "استعادة",
        "License Expire Date": "تاريخ انتهاء الترخيص",
        "License Expiration Notice": "تنبيه انتهاء الترخيص",
        "Expires on": "ينتهي في",
        "days left": "يوم متبقي",
        "Super admin only": "للمشرف الأعلى فقط",
        "Entity Scope": "نطاق الجهة",
        "Diff": "الفروقات",
        "View Diff": "عرض الفروقات",
        "Import CSV": "استيراد CSV",
        "Realtime Alerts": "تنبيهات فورية",
        "Clear All": "إلغاء الكل",
        "Select All": "تحديد الكل",
        "Type name": "اكتب الاسم",
        "Type id": "اكتب المعرف",
        "Type civil id": "اكتب الرقم المدني",
        "Type employee number": "اكتب رقم الموظف",
        "Type employee": "اكتب الموظف",
        "Type location": "اكتب الموقع",
        "Type user": "اكتب المستخدم",
        "Type description": "اكتب الوصف",
        "Type field value": "اكتب قيمة الحقل",
        "e.g. HQ": "مثال: المقر الرئيسي",
        "Search...": "ابحث...",
        "username / name / email": "اسم المستخدم / الاسم / البريد الإلكتروني",
        "Leave blank to keep": "اتركه فارغًا للاحتفاظ بالقيمة",
        "Show Images": "إظهار الصور",
        "Hide Images": "إخفاء الصور",
        "Show Image": "إظهار الصورة",
        "Close": "إغلاق",
        "Loading...": "جارٍ التحميل...",
        "No image available.": "لا توجد صورة متاحة.",
        "Employee Working Hours (Expected vs Actual)": "ساعات عمل الموظفين (المتوقعة مقابل الفعلية)",
        "Employees": "الموظفون",
        "Expected Hours": "الساعات المتوقعة",
        "Actual Hours": "الساعات الفعلية",
        "Variance Hours": "فرق الساعات",
        "Compliance %": "نسبة الالتزام %",
        "Days": "الأيام",
        "No working-hours data found for current filters.": "لا توجد بيانات ساعات عمل للفلاتر الحالية.",
    },
    "es": {
        "Admin Login": "Inicio de sesión de administrador",
        "Sign in using an admin account to access the dashboard.": "Inicia sesión con una cuenta de administrador para acceder al panel.",
        "Invalid credentials or not an admin user.": "Credenciales inválidas o el usuario no es administrador.",
        "Back": "Volver",
        "Username": "Usuario",
        "Password": "Contraseña",
        "Language": "Idioma",
        "Menu": "Menú",
        "Sign In": "Iniciar sesión",
        "Logout": "Cerrar sesión",
        "Admin Home": "Inicio de administración",
        "Manage all registered models from one page.": "Gestiona todos los modelos registrados desde una sola página.",
        "Dashboard": "Panel",
        "Reports": "Reportes",
        "Open Django Admin": "Abrir Django Admin",
        "Privileges Matrix": "Matriz de privilegios",
        "Audit Insights": "Información de auditoría",
        "Attendance Exceptions": "Excepciones de asistencia",
        "Manage": "Gestionar",
        "No admin models available for your permissions.": "No hay modelos disponibles para tus permisos.",
        "Model is not available in Django admin URLs.": "El modelo no está disponible en las URLs de Django admin.",
        "Insert and edit records.": "Insertar y editar registros.",
        "Home": "Inicio",
        "Add New": "Agregar nuevo",
        "Search Name": "Buscar nombre",
        "Search ID": "Buscar ID",
        "Filter Date": "Filtrar fecha",
        "Search Civil ID": "Buscar Civil ID",
        "Search Employee Number": "Buscar número de empleado",
        "Search Employee": "Buscar empleado",
        "Search Location": "Buscar ubicación",
        "Search User": "Buscar usuario",
        "Search Description": "Buscar descripción",
        "Actions": "Acciones",
        "Edit": "Editar",
        "No records yet.": "Sin registros todavía.",
        "First": "Primera",
        "Previous": "Anterior",
        "Next": "Siguiente",
        "Last": "Última",
        "List Page": "Página de lista",
        "Cancel": "Cancelar",
        "Search options...": "Buscar opciones...",
        "Select User": "Seleccionar usuario",
        "Apply": "Aplicar",
        "Model": "Modelo",
        "Access Level": "Nivel de acceso",
        "Enabled": "Habilitado",
        "Save Matrix": "Guardar matriz",
        "No Access": "Sin acceso",
        "NO_ACCESS": "Sin acceso",
        "ALL_MODELS": "TODOS_LOS_MODELOS",
        "Read Only": "Solo lectura",
        "READ_ONLY": "Solo lectura",
        "Add Only": "Solo agregar",
        "ADD_ONLY": "Solo agregar",
        "Edit Only": "Solo editar",
        "EDIT_ONLY": "Solo editar",
        "All": "Todos",
        "ALL": "Todos",
        "Full Admin": "Administrador total",
        "FULL_ADMIN": "Administrador total",
        "Manage user privileges in one matrix by model.": "Gestiona privilegios de usuario en una sola matriz por modelo.",
        "Select a user to view and edit privileges.": "Selecciona un usuario para ver y editar privilegios.",
        "Read only access. Only FULL_ADMIN can update privileges.": "Acceso de solo lectura. Solo FULL_ADMIN puede actualizar privilegios.",
        "Generate PDF reports for your entity data.": "Generar reportes PDF para los datos de tu entidad.",
        "Audit Logs": "Registros de auditoría",
        "Employee Location Assignments": "Asignaciones de empleado a ubicación",
        "Includes assignment status, sign permissions, and start/end dates.": "Incluye estado de asignación, permisos de marcación y fechas de inicio/fin.",
        "Employee": "Empleado",
        "All Employees": "Todos los empleados",
        "Location": "Ubicación",
        "All Locations": "Todas las ubicaciones",
        "Active": "Activo",
        "All": "Todos",
        "Yes": "Sí",
        "No": "No",
        "Preview": "Vista previa",
        "Download PDF": "Descargar PDF",
        "Locations": "Ubicaciones",
        "Includes location activity, GPS/beacon mode, coordinates, and radius.": "Incluye actividad de ubicación, modo GPS/beacon, coordenadas y radio.",
        "Includes location activity, GPS/beacon mode, and coordinates.": "Incluye actividad de ubicación, modo GPS/beacon y coordenadas.",
        "Name Contains": "Nombre contiene",
        "GPS Based": "Basado en GPS",
        "Beacon Based": "Basado en Beacon",
        "No filters applied.": "Sin filtros aplicados.",
        "No records found for current filters.": "No se encontraron registros para los filtros actuales.",
        "Apply Filter": "Aplicar filtro",
        "Clear": "Limpiar",
        "From Date": "Desde fecha",
        "To Date": "Hasta fecha",
        "Total Transactions": "Total de transacciones",
        "Today Transactions": "Transacciones de hoy",
        "Total Failures": "Total de fallos",
        "Biometric Verification Failures": "Fallos de verificación biométrica",
        "Total Locations": "Total de ubicaciones",
        "Sign Actions": "Acciones de marcación",
        "Failed Verifications": "Verificaciones fallidas",
        "Failed Biometric Verifications": "Verificaciones biométricas fallidas",
        "Note: failures here mean biometric verification failed, but attendance transaction was still inserted.": "Nota: los fallos aquí significan que la verificación biométrica falló, pero la transacción de asistencia sí fue insertada.",
        "SIGN_IN Failed": "SIGN_IN fallido",
        "SIGN_CONFIRM Failed": "SIGN_CONFIRM fallido",
        "SIGN_OUT Failed": "SIGN_OUT fallido",
        "Top 50 Employees With Failed Biometric Verification": "Top 50 empleados con verificación biométrica fallida",
        "Employee ID": "ID del empleado",
        "Employee Name": "Nombre del empleado",
        "Employee No": "N.° de empleado",
        "Civil ID": "ID civil",
        "Failed Count": "Cantidad de fallos",
        "Last Failed At": "Último fallo en",
        "No failed biometric records found.": "No se encontraron registros de fallos biométricos.",
        "Charts": "Gráficos",
        "Top Locations by Transactions": "Top ubicaciones por transacciones",
        "Failed Transactions": "Transacciones fallidas",
        "Inactive": "Inactivo",
        "Entity Logo": "Logo de la entidad",
        "Powered by AWS": "Con tecnología de AWS",
        "Owned by SWAP KUWAIT": "Propiedad de SWAP KUWAIT",
        "Quick Search": "Búsqueda rápida",
        "Entity": "Entidad",
        "User": "Usuario",
        "Page": "Página",
        "Action": "Acción",
        "of": "de",
        "Total Audit Logs": "Total de registros de auditoría",
        "Unique Users": "Usuarios únicos",
        "Permission Denied Events": "Eventos de permiso denegado",
        "Action Contains": "Acción contiene",
        "Model Contains": "Modelo contiene",
        "Description Contains": "Descripción contiene",
        "Export CSV": "Exportar CSV",
        "Export PDF": "Exportar PDF",
        "Top Actions": "Principales acciones",
        "Top Models": "Principales modelos",
        "Audit Log Details": "Detalles del registro de auditoría",
        "Created At": "Creado en",
        "Object ID": "ID de objeto",
        "Description": "Descripción",
        "No audit logs found for current filters.": "No se encontraron registros de auditoría para los filtros actuales.",
        "Review audit activity with filters, metrics, and exports.": "Revisa actividad de auditoría con filtros, métricas y exportaciones.",
        "Review attendance anomalies to follow up quickly.": "Revisa anomalías de asistencia para dar seguimiento rápido.",
        "Failure Threshold": "Umbral de fallos",
        "Late After Hour": "Tarde después de la hora",
        "Late SIGN_IN Groups": "Grupos de SIGN_IN tardíos",
        "Missing SIGN_OUT By Day": "Falta de SIGN_OUT por día",
        "Outside Assigned Locations": "Fuera de ubicaciones asignadas",
        "Repeated Biometric Failures": "Fallos biométricos repetidos",
        "Date": "Fecha",
        "SIGN_IN Count": "Cantidad SIGN_IN",
        "SIGN_OUT Count": "Cantidad SIGN_OUT",
        "Last SIGN_IN": "Último SIGN_IN",
        "Transaction ID": "ID de transacción",
        "Occurred At": "Ocurrió en",
        "No exception records found for current filters.": "No se encontraron excepciones para los filtros actuales.",
        "Biometric Verification Failures": "Fallos de verificación biométrica",
        "Failed Biometric Verifications": "Verificaciones biométricas fallidas",
        "SIGN_IN Failed": "SIGN_IN fallido",
        "SIGN_CONFIRM Failed": "SIGN_CONFIRM fallido",
        "SIGN_OUT Failed": "SIGN_OUT fallido",
        "Employee ID": "ID del empleado",
        "Employee Name": "Nombre del empleado",
        "Employee No": "N.° de empleado",
        "Civil ID": "ID civil",
        "Failed Count": "Cantidad de fallos",
        "Last Failed At": "Último fallo en",
        "No failed biometric records found.": "No se encontraron registros de fallos biométricos.",
        "Inactive": "Inactivo",
        "Entity Logo": "Logo de la entidad",
        "Powered by AWS": "Con tecnología de AWS",
        "Owned by SWAP KUWAIT": "Propiedad de SWAP KUWAIT",
        "Note: failures here mean biometric verification failed, but attendance transaction was still inserted.": "Nota: los fallos aquí significan que la verificación biométrica falló, pero la transacción de asistencia sí fue insertada.",
        "Save Filters": "Guardar filtros",
        "Load Saved Filters": "Cargar filtros guardados",
        "Clear Saved Filters": "Limpiar filtros guardados",
        "Data Quality Checks": "Controles de calidad de datos",
        "Employees Missing Photo": "Empleados sin foto",
        "Duplicate Civil ID Groups": "Grupos de ID civil duplicado",
        "Duplicate Employee No Groups": "Grupos de N.° de empleado duplicado",
        "GPS Locations Missing Coordinates": "Ubicaciones GPS sin coordenadas",
        "Inactive Employees With Active Assignments": "Empleados inactivos con asignaciones activas",
        "Biometric API Health": "Salud de API biométrica",
        "Health metrics are computed from attendance records that used FACE_COMPARE_API in the selected date range.": "Las métricas de salud se calculan a partir de registros de asistencia que usaron FACE_COMPARE_API en el rango de fechas seleccionado.",
        "Total API Checks": "Total de verificaciones API",
        "Passed Checks": "Verificaciones aprobadas",
        "Failed Checks": "Verificaciones fallidas",
        "Liveness Failures": "Fallos de liveness",
        "Liveness": "Liveness",
        "Face Compare Failures": "Fallos de comparación facial",
        "Last API Failure At": "Último fallo API en",
        "Success Rate": "Tasa de éxito",
        "Error Rate": "Tasa de error",
        "Change Summary": "Resumen de cambios",
        "Field": "Campo",
        "Old Value": "Valor anterior",
        "New Value": "Valor nuevo",
        "No field changes detected.": "No se detectaron cambios en campos.",
        "Recommended: PNG/JPG, max 1 MB, square logo (e.g. 256x256).": "Recomendado: PNG/JPG, máximo 1 MB, logo cuadrado (ej. 256x256).",
        "Approx size": "Tamaño aprox.",
        "Dimensions": "Dimensiones",
        "Warning: logo is larger than recommended 1 MB.": "Advertencia: el logo supera el tamaño recomendado de 1 MB.",
        "Deactivate": "Desactivar",
        "Restore": "Restaurar",
        "License Expire Date": "Fecha de vencimiento de licencia",
        "License Expiration Notice": "Aviso de vencimiento de licencia",
        "Expires on": "Vence el",
        "days left": "días restantes",
        "Super admin only": "Solo superadministrador",
        "Entity Scope": "Alcance de entidad",
        "Diff": "Diferencias",
        "View Diff": "Ver diferencias",
        "Import CSV": "Importar CSV",
        "Realtime Alerts": "Alertas en tiempo real",
        "Clear All": "Limpiar todo",
        "Select All": "Seleccionar todo",
        "Type name": "Escriba el nombre",
        "Type id": "Escriba el ID",
        "Type civil id": "Escriba el ID civil",
        "Type employee number": "Escriba el numero de empleado",
        "Type employee": "Escriba el empleado",
        "Type location": "Escriba la ubicacion",
        "Type user": "Escriba el usuario",
        "Type description": "Escriba la descripcion",
        "Type field value": "Escriba el valor del campo",
        "e.g. HQ": "ej. Sede",
        "Search...": "Buscar...",
        "username / name / email": "usuario / nombre / correo",
        "Leave blank to keep": "Dejar vacio para mantener",
        "Show Images": "Mostrar imagenes",
        "Hide Images": "Ocultar imagenes",
        "Show Image": "Mostrar imagen",
        "Close": "Cerrar",
        "Loading...": "Cargando...",
        "No image available.": "No hay imagen disponible.",
        "Employee Working Hours (Expected vs Actual)": "Horas de trabajo del empleado (esperadas vs reales)",
        "Employees": "Empleados",
        "Expected Hours": "Horas esperadas",
        "Actual Hours": "Horas reales",
        "Variance Hours": "Diferencia de horas",
        "Compliance %": "Cumplimiento %",
        "Days": "Días",
        "No working-hours data found for current filters.": "No se encontraron datos de horas de trabajo para los filtros actuales.",
    },
}


@register.simple_tag(takes_context=True)
def tr(context, text):
    request = context.get("request")
    lang = "en"
    if request is not None:
        lang = (request.session.get("ui_lang") or "en").lower()
    if lang not in ("en", "ar", "es"):
        lang = "en"
    return _TRANSLATIONS.get(lang, {}).get(text, text)
