# Generated by Django 6.0.1 on 2026-01-29 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_no', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('biometric_enrolled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='basmaapp.entity')),
            ],
            options={
                'unique_together': {('entity', 'employee_no')},
            },
        ),
        migrations.CreateModel(
            name='EntitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entity_logos/')),
                ('location_mode', models.CharField(choices=[('GPS', 'GPS'), ('BEACON', 'BEACON'), ('BOTH', 'BOTH')], default='GPS', max_length=10)),
                ('gps_radius_meters', models.PositiveIntegerField(default=100)),
                ('require_gps_high_accuracy', models.BooleanField(default=True)),
                ('beacon_rssi_threshold', models.IntegerField(default=-75)),
                ('beacon_min_count', models.PositiveIntegerField(default=1)),
                ('require_confirm', models.BooleanField(default=True)),
                ('allow_multiple_sessions_per_day', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='basmaapp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_radius_meters', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='basmaapp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CANCELED', 'CANCELED')], default='OPEN', max_length=10)),
                ('sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('sign_confirm_at', models.DateTimeField(blank=True, null=True)),
                ('sign_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='basmaapp.employee')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='basmaapp.entity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basmaapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_assignments', to='basmaapp.employee')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='basmaapp.entity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='basmaapp.location')),
            ],
            options={
                'unique_together': {('employee', 'location')},
            },
        ),
        migrations.CreateModel(
            name='BeaconDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('uuid', models.CharField(max_length=64)),
                ('major', models.PositiveIntegerField(blank=True, null=True)),
                ('minor', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='basmaapp.entity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='basmaapp.location')),
            ],
            options={
                'unique_together': {('entity', 'uuid', 'major', 'minor')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SIGN_IN', 'SIGN_IN'), ('SIGN_CONFIRM', 'SIGN_CONFIRM'), ('SIGN_OUT', 'SIGN_OUT')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('beacon_uuid', models.CharField(blank=True, max_length=64)),
                ('beacon_major', models.PositiveIntegerField(blank=True, null=True)),
                ('beacon_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('beacon_rssi', models.IntegerField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('biometric_verify', models.CharField(choices=[('PENDING', 'PENDING'), ('PASSED', 'PASSED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('biometric_method', models.CharField(blank=True, max_length=50)),
                ('biometric_error', models.CharField(blank=True, max_length=300)),
                ('request_nonce', models.CharField(blank=True, max_length=120)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='basmaapp.attendancesession')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_transactions', to='basmaapp.employee')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_transactions', to='basmaapp.entity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basmaapp.location')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'employee', 'occurred_at'], name='basmaapp_at_entity__9c63b3_idx'), models.Index(fields=['entity', 'action', 'occurred_at'], name='basmaapp_at_entity__7729ee_idx')],
            },
        ),
    ]
