# Generated by Django 6.0.1 on 2026-01-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0002_alter_employee_employee_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device_bound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
