# Generated by Django 6.0.1 on 2026-01-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0003_employee_device_bound_at_employee_device_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancetransaction',
            name='session',
        ),
        migrations.AddField(
            model_name='employeelocationassignment',
            name='beacon_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basmaapp.beacondevice'),
        ),
        migrations.AddField(
            model_name='employeelocationassignment',
            name='is_GPS_based',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeelocationassignment',
            name='is_beacon_based',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
    ]
