# Generated by Django 6.0.1 on 2026-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0004_remove_attendancetransaction_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='civil_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
