# Generated by Django 6.0.1 on 2026-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0007_inboxmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetransaction',
            name='photo_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_base64',
            field=models.TextField(blank=True),
        ),
    ]
