# Generated by Django 6.0.1 on 2026-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0008_attendancetransaction_photo_base64_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitysettings',
            old_name='require_confirm',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='entitysettings',
            name='allow_multiple_sessions_per_day',
        ),
        migrations.RemoveField(
            model_name='entitysettings',
            name='beacon_min_count',
        ),
        migrations.RemoveField(
            model_name='entitysettings',
            name='beacon_rssi_threshold',
        ),
        migrations.RemoveField(
            model_name='entitysettings',
            name='gps_radius_meters',
        ),
        migrations.RemoveField(
            model_name='entitysettings',
            name='location_mode',
        ),
        migrations.RemoveField(
            model_name='entitysettings',
            name='require_gps_high_accuracy',
        ),
        migrations.AddField(
            model_name='entitysettings',
            name='number_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
