# Generated by Django 6.0.1 on 2026-02-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0009_rename_require_confirm_entitysettings_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitysettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='entitysettings',
            name='logo64',
            field=models.TextField(blank=True),
        ),
    ]
