# Generated by Django 6.0.1 on 2026-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0010_remove_entitysettings_logo_entitysettings_logo64'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitysettings',
            name='theme_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
