# Generated by Django 6.0.1 on 2026-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0011_entitysettings_theme_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelocationassignment',
            name='is_GPS_based',
        ),
        migrations.RemoveField(
            model_name='employeelocationassignment',
            name='is_beacon_based',
        ),
        migrations.AddField(
            model_name='location',
            name='beacon_uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='location',
            name='is_GPS_based',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_beacon_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='major_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='minor_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='rssi_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
