# Generated by Django 6.0.1 on 2026-02-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0012_remove_employeelocationassignment_is_gps_based_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelocationassignment',
            name='beacon_device',
        ),
        migrations.DeleteModel(
            name='BeaconDevice',
        ),
    ]
