# Generated by Django 6.0.1 on 2026-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0013_remove_employeelocationassignment_beacon_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocationassignment',
            name='allow_sign_confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeelocationassignment',
            name='allow_sign_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeelocationassignment',
            name='allow_sign_out',
            field=models.BooleanField(default=True),
        ),
    ]
