# Generated by Django 6.0.1 on 2026-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0014_employeelocationassignment_allow_sign_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='confirm_sign_period_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
