# Generated by Django 6.0.1 on 2026-02-10 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0015_employee_confirm_sign_period_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetransaction',
            name='transaction_comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='basmaapp.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
