# Generated by Django 6.0.1 on 2026-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0016_attendancetransaction_transaction_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number_working_hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
