# Generated by Django 6.0.1 on 2026-02-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0017_employee_number_working_hours_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number_working_hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=7.0, max_digits=4, null=True),
        ),
    ]
