# Generated by Django 6.0.1 on 2026-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0018_alter_employee_number_working_hours_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetransaction',
            name='beacon_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='attendancetransaction',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendancetransaction',
            name='transaction_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
