# Generated by Django 5.0.10 on 2026-02-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basmaapp", "0019_alter_attendancetransaction_beacon_uuid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="basmaapp.entity"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["entity", "created_at"], name="basmaapp_au_entity__f59541_idx"),
                    models.Index(fields=["user", "created_at"], name="basmaapp_au_user_id_7f3171_idx"),
                    models.Index(fields=["model_name", "created_at"], name="basmaapp_au_model_n_96c74d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPrivilege",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "model_name",
                    models.CharField(blank=True, help_text="Leave blank for all models", max_length=100),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("READ_ONLY", "Read Only"),
                            ("ADD_ONLY", "Add Only"),
                            ("EDIT_ONLY", "Edit Only"),
                            ("ALL", "All"),
                        ],
                        default="READ_ONLY",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_privileges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_privileges", to="basmaapp.entity"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_privileges", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("entity", "user", "model_name")},
            },
        ),
    ]
