# Generated by Django 5.0.10 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basmaapp", "0020_userprivilege_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprivilege",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("READ_ONLY", "Read Only"),
                    ("ADD_ONLY", "Add Only"),
                    ("EDIT_ONLY", "Edit Only"),
                    ("ALL", "All"),
                    ("FULL_ADMIN", "Full Admin"),
                ],
                default="READ_ONLY",
                max_length=20,
            ),
        ),
    ]
