# Generated by Django 6.0.1 on 2026-02-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0021_alter_userprivilege_access_level'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='audit',
            new_name='basmaapp_au_entity__933f9e_idx',
            old_name='basmaapp_au_entity__f59541_idx',
        ),
        migrations.RenameIndex(
            model_name='audit',
            new_name='basmaapp_au_user_id_a7415d_idx',
            old_name='basmaapp_au_user_id_7f3171_idx',
        ),
        migrations.RenameIndex(
            model_name='audit',
            new_name='basmaapp_au_model_n_ecf374_idx',
            old_name='basmaapp_au_model_n_96c74d_idx',
        ),
    ]
