# Generated by Django 6.0.1 on 2026-02-17 10:50

from django.db import migrations, models


def copy_location_radius_to_assignments(apps, schema_editor):
    Location = apps.get_model("basmaapp", "Location")
    EmployeeLocationAssignment = apps.get_model("basmaapp", "EmployeeLocationAssignment")
    for assignment in EmployeeLocationAssignment.objects.select_related("location").all():
        location = assignment.location
        if location is None:
            continue
        assignment.gps_radius_meters = getattr(location, "gps_radius_meters", 100) or 100
        assignment.save(update_fields=["gps_radius_meters"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0025_alter_entity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocationassignment',
            name='gps_radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.RunPython(copy_location_radius_to_assignments, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name='location',
            name='gps_radius_meters',
        ),
    ]
