# Generated by Django 6.0.1 on 2026-02-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0026_remove_location_gps_radius_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocationassignment',
            name='period_to_take_action',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
