# Generated by Django 5.0.10 on 2026-04-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0038_mobileactivationrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='managerqrcodetoken',
            new_name='basmaapp_ma_entity__3caab0_idx',
            old_name='basmaapp_ma_entity__1d37b2_idx',
        ),
        migrations.RenameIndex(
            model_name='managerqrcodetoken',
            new_name='basmaapp_ma_token_821b56_idx',
            old_name='basmaapp_ma_token_a18fed_idx',
        ),
        migrations.RenameIndex(
            model_name='managerqrcodetoken',
            new_name='basmaapp_ma_expires_a0bf20_idx',
            old_name='basmaapp_ma_expires_8dda2f_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileactivationrequest',
            new_name='basmaapp_mo_entity__e33779_idx',
            old_name='basmaapp_mo_entity__534f70_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileactivationrequest',
            new_name='basmaapp_mo_employe_066daf_idx',
            old_name='basmaapp_mo_employe_ee34fe_idx',
        ),
    ]
