# Generated by Django 5.2 on 2026-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basmaapp', '0040_entitysettings_face_checks_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_review_mode', models.BooleanField(default=False, help_text='When enabled, verify-uuid skips UUID matching and returns the Employee linked to Django User id=1.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App global settings',
            },
        ),
    ]
